title: Switch2OSM
description: >
  Переходите на OpenStreetMap и узнайте, как сделать красивые карты из лучших в мире геоданных.
baseurl: "" # the subpath of your site, e.g. /blog
copyright: 2013–2019 OpenStreetMap and contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC BY-SA</a>
url: http://use.openstreetmap.ru
github_username: switch2osm

# Build settings
markdown: kramdown

# Repo files to not include in built site
exclude:
  - Dockerfile*
  - docker-compose.*
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

menu:
  - title: Зачем переходить?
    url: /why-switch/
  - title: Уже на OSM
    url: /case-studies/
  - title: Основы
    url: /the-basics/
  - title: Тайлы
    url: /using-tiles/
  - title: Делаем свои тайлы
    url: /serving-tiles/
  - title: Иное
    url: /other-uses/
  - title: Провайдеры
    url: /providers/
  - title: Узнайте больше
    url: /find-out-more/
